### ISSUE TITLE
Ethernet.linkState() returns a bool

### ISSUE THREAD

**Issue by ssilverman** [ynformatics/multiplexer#1]
Nice project! I always enjoy seeing what people have done with libraries I’ve made.

https://github.com/ynformatics/multiplexer/blob/121092748404b3fbe8870042e2f75b832d81155b/multiplexer.ino#L147

This function returns a Boolean, not an `EthernetLinkStatus`. While your code technically works because I purposely made `LinkOFF` zero (note that other libraries might define this enum value as something non-zero, eg. see here: https://github.com/vjmuzik/NativeEthernet/blob/cdf6b3a2b5d62559a7c76be5b9d3fa60cf9d686b/src/NativeEthernet.h#L60), you’re comparing two different types.

Either:
```c++
while (!Ethernet.linkState()) {
```

Or:
```
while (Ethernet.linkStatus() != LinkON) {
```

Remember that there’s technically also the `Unknown` value to consider; that’s why I suggest comparing to “not ON”.

**Comment by ynformatics** [comment]
Thanks, and thanks for making your QNEthernet library available!
I've now fixed that issue.

**Comment by ssilverman** [comment]
It looks like the issue still exists in your latest commit. The code should be `while (!Ethernet.linkState())`. It’s <code>link***Status***()</code> that can be compared with those enum values. :)

I guess I made the API confusing to look at…

(Ref: https://github.com/ynformatics/multiplexer/commit/7b2a617dc472f3ba6a6bb361c71b93035034a855)
